### ISSUE TITLE
Are there any possible conflicts when using this with Laravel Fortify and Laravel Sanctum? 

### ISSUE THREAD

**Issue by DoctorEaker** [lucidarch/getting-started-micro#1]
I'm sorry if the question is stupid or too obvious, but I'm new to this architecture, I've been reading your docs for a while now, and I find Lucidarch to be a really clean architecture, so I wonder if there will be any problem if using Fortify and Sanctum with Lucidarch...

Thanks a lot and keep the good work!

**Comment by Batisska** [comment]
[My test project](https://github.com/Batisska/library) 

I have implemented laravel sanctum.

**Comment by Mulkave** [comment]
@DoctorEaker there shouldn't be any conflicts when using anything from Laravel, all packages, add-ons and other libraries should work as-is. Lucid doesn't interfere nor enforce any code, it's just a matter of organising the code you're writing in a clear and readable manner. Good luck!
